<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Migration 7 — Create the `source_charts` table.
 *
 * Tracks a chart PNG generated by observatory-pipeline. Originally only the
 * per-source finder/discovery chart from modules/finder_chart.py — a track
 * chart (numbered epoch positions + motion line on one background frame)
 * for moving objects (ASTEROID/COMET/MOVING_UNKNOWN/SPACE_DEBRIS), a stamp
 * strip (one small crop per epoch, each circled) for stationary anomalies
 * with 2+ epochs, or a before/after pair for a source seen on only a single
 * epoch so far (added 2026-08-06, same day, to the `style` ENUM below — see
 * finder_chart.py's `_style_for_source()`).
 *
 * Extended (still same migration — no DB has run this yet at the time of
 * that change) to also track the PREVIEW_CATALOG_MATCH task type's
 * diagnostic chart (modules/catalog_preview.py): that one has no source at
 * all — it's a whole-frame image, not tied to any celestial object — so it
 * identifies its row by `task_item_id` instead. Exactly one of
 * `source_id`/`task_item_id` is set per row; there is no meaningful
 * "neither" or "both" state, though nothing below enforces that with a CHECK
 * constraint (MariaDB 10.5 supports one, but the two existing call sites
 * already only ever set one or the other, so it would be pure redundant
 * insurance against a bug that would show up immediately in testing anyway).
 *
 * The rendered image bytes themselves are NOT stored in this table — they
 * live on disk under writable/uploads/charts/{source_id|task_item_id}.png
 * (see SourcesController::uploadChart()/chart() and
 * TasksController::uploadItemChart()/itemChart()) and are always
 * regenerated from scratch on every request rather than patched in place,
 * so this table only needs to track *that* a chart exists and a little
 * metadata about it.
 */
class CreateSourceChartsTable extends Migration
{
    public function up(): void
    {
        $this->forge->addField([
            'id' => [
                'type'       => 'CHAR',
                'constraint' => 24,
            ],
            'source_id' => [
                'type'       => 'CHAR',
                'constraint' => 24,
                'null'       => true,
            ],
            // Set instead of source_id for a PREVIEW_CATALOG_MATCH chart —
            // see this migration's class docblock. Nullable for the same
            // reason source_id is: exactly one of the two is set per row.
            'task_item_id' => [
                'type'       => 'CHAR',
                'constraint' => 24,
                'null'       => true,
            ],
            // Which rendering style was used for the current file on disk —
            // informational (the pipeline decides the style, not the API),
            // but useful for the future website to know how to caption it.
            // 'catalog_preview' (added alongside task_item_id above) is the
            // only style that pairs with task_item_id rather than source_id.
            'style' => [
                'type'       => 'ENUM',
                'constraint' => ['track', 'stamp_strip', 'before_after', 'catalog_preview'],
                'null'       => false,
            ],
            // Number of epochs actually included in the current image (a
            // subtraction of the requested epoch count when some archived
            // FITS files were missing locally — see finder_chart.py).
            // Meaningless for 'catalog_preview' (a single-frame chart, not
            // an epoch series) — always 1 for that style, kept rather than
            // making the column nullable just for one style.
            'frame_count' => [
                'type'       => 'INT',
                'constraint' => 11,
                'null'       => false,
                'default'    => 0,
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'created_at' => [
                'type'    => 'DATETIME',
                'null'    => true,
                'default' => null,
            ],
        ]);

        $this->forge->addPrimaryKey('id');
        // One chart per source / per task item — upsertForSource()/
        // upsertForTaskItem() upsert by whichever column applies. NULL is
        // not considered equal to NULL by MySQL/MariaDB unique indexes, so
        // the many rows with source_id=NULL (all the catalog_preview ones)
        // never collide with each other on this key — same reasoning as
        // `sources`.`uniq_sources_catalog_identity`.
        $this->forge->addUniqueKey('source_id', 'uq_source_charts_source');
        $this->forge->addUniqueKey('task_item_id', 'uq_source_charts_task_item');

        // A source being removed from the catalog should take its chart
        // with it — unlike anomalies.source_id (SET NULL), there is no
        // meaningful "chart with no source" state to preserve.
        $this->forge->addForeignKey('source_id', 'sources', 'id', 'CASCADE', 'CASCADE');
        // Deliberately NO foreign key from task_item_id to task_items.id,
        // unlike source_id above: this migration (2026-08-06) runs BEFORE
        // 2026-08-07-000001_CreateTasksTable.php in migration order (by
        // filename/date), so `task_items` doesn't exist yet at the point
        // this file's up() runs on a fresh database — a FK to it here would
        // fail at CREATE TABLE time. The UNIQUE key above still gives fast
        // lookup and enforces one-chart-per-task-item; it just doesn't
        // enforce referential integrity or cascade-delete at the DB level.
        // In practice this is a small gap: task_items rows are never
        // deleted individually, only cascaded when their parent `tasks` row
        // is deleted, and that path would orphan this table's row rather
        // than clean it up. If that ever matters, the fix is to move this
        // migration's timestamp after CreateTasksTable's (or add the FK in
        // a follow-up migration), not to patch it in here.

        // No explicit CHARSET/COLLATE here — `sources`/`frames`/`anomalies`
        // were all created without one too, so they inherit the active DB
        // connection's default charset (utf8mb4/utf8mb4_general_ci per
        // app/Config/Database.php's 'default' group). A char/varchar FK
        // column whose charset+collation don't exactly match the referenced
        // column's raises MySQL/MariaDB errno 150 ("foreign key constraint
        // is incorrectly formed") at CREATE TABLE time, so this table must
        // pick up the same default rather than pinning its own.
        $this->forge->createTable('source_charts', true, [
            'ENGINE' => 'InnoDB',
        ]);

        $this->db->query('ALTER TABLE `source_charts` MODIFY `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP');
    }

    public function down(): void
    {
        $this->forge->dropTable('source_charts', true);
    }
}
