<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Migration 7 — Create the `source_charts` table.
 *
 * Tracks the finder/discovery-chart PNG generated by observatory-pipeline's
 * modules/finder_chart.py for a given source_id: a track chart (numbered
 * epoch positions + motion line on one background frame) for moving objects
 * (ASTEROID/COMET/MOVING_UNKNOWN/SPACE_DEBRIS), a stamp strip (one small
 * crop per epoch, each circled) for stationary anomalies with 2+ epochs, or
 * a before/after pair for a source seen on only a single epoch so far
 * (added 2026-08-06, same day, to the `style` ENUM below — see
 * finder_chart.py's `_style_for_source()`).
 *
 * The rendered image bytes themselves are NOT stored in this table — they
 * live on disk under writable/uploads/charts/{source_id}.png (see
 * SourcesController::uploadChart()/chart()) and are always regenerated from
 * scratch on every new epoch rather than patched in place, so this table
 * only needs to track *that* a chart exists and a little metadata about it.
 */
class CreateSourceChartsTable extends Migration
{
    public function up(): void
    {
        $this->forge->addField([
            'id' => [
                'type'       => 'CHAR',
                'constraint' => 24,
            ],
            'source_id' => [
                'type'       => 'CHAR',
                'constraint' => 24,
                'null'       => false,
            ],
            // Which rendering style was used for the current file on disk —
            // informational (the pipeline decides the style, not the API),
            // but useful for the future website to know how to caption it.
            'style' => [
                'type'       => 'ENUM',
                'constraint' => ['track', 'stamp_strip', 'before_after'],
                'null'       => false,
            ],
            // Number of epochs actually included in the current image (a
            // subtraction of the requested epoch count when some archived
            // FITS files were missing locally — see finder_chart.py).
            'frame_count' => [
                'type'       => 'INT',
                'constraint' => 11,
                'null'       => false,
                'default'    => 0,
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'created_at' => [
                'type'    => 'DATETIME',
                'null'    => true,
                'default' => null,
            ],
        ]);

        $this->forge->addPrimaryKey('id');
        // One chart per source — uploadChart() upserts by source_id.
        $this->forge->addUniqueKey('source_id', 'uq_source_charts_source');

        // A source being removed from the catalog should take its chart
        // with it — unlike anomalies.source_id (SET NULL), there is no
        // meaningful "chart with no source" state to preserve.
        $this->forge->addForeignKey('source_id', 'sources', 'id', 'CASCADE', 'CASCADE');

        // No explicit CHARSET/COLLATE here — `sources`/`frames`/`anomalies`
        // were all created without one too, so they inherit the active DB
        // connection's default charset (utf8mb4/utf8mb4_general_ci per
        // app/Config/Database.php's 'default' group). A char/varchar FK
        // column whose charset+collation don't exactly match the referenced
        // column's raises MySQL/MariaDB errno 150 ("foreign key constraint
        // is incorrectly formed") at CREATE TABLE time, so this table must
        // pick up the same default rather than pinning its own.
        $this->forge->createTable('source_charts', true, [
            'ENGINE' => 'InnoDB',
        ]);

        $this->db->query('ALTER TABLE `source_charts` MODIFY `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP');
    }

    public function down(): void
    {
        $this->forge->dropTable('source_charts', true);
    }
}
